name: Docker Package

on:
  release:
    types: [created]
    
jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
      - uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12
      - working-directory: ./sample-packages/docker
        run: |
          docker build -t sample .
      - working-directory: ./sample-packages/docker
        run: |
          echo ${{secrets.GITHUB_TOKEN}} | docker login ghcr.io -u cunla --password-stdin
          docker tag sample ghcr.io/cunla/exercise-publish-package:latest
          docker push ghcr.io/cunla/exercise-publish-package:latest
